# -*- coding: utf-8 -*-
"""Voxelmorph_Model_Summary.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K2LlgrWXll82wU8G2-F4aF4-6gjz5IAM
"""

import tensorflow as tf

!pip install voxelmorph

import voxelmorph as vxm
import neurite as ne

"""# Data"""

# our data will be of shape 160 x 192 x 224
vol_shape = (160, 192, 224)
nb_features = [
    [32, 32, 32, 32, 32],
    [32, 32, 32, 32, 32, 32, 16, 16]
]
# build vxm network
vxm_model = vxm.networks.VxmDense(vol_shape, nb_features, int_steps=0);
vxm_model.summary(line_length = 200)

vxm_model.inputs

vxm_model.outputs